config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :prices
  resources :currencies
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
  belongs_to :currency
  validates :ht, :ttc, presence: true
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def price_params
      params.require(:price).permit(:product_id, :currency_id, :ht, :ttc)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: price, local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
        <% price.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :currency_id %>
    <%= form.text_field :currency_id %>
  </div>

  <div class="field">
    <%= form.label :ht %>
    <%= form.text_field :ht %>
  </div>

  <div class="field">
    <%= form.label :ttc %>
    <%= form.text_field :ttc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Currency</th>
      <th>Ht</th>
      <th>Ttc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.product_id %></td>
        <td><%= price.currency_id %></td>
        <td><%= price.ht %></td>
        <td><%= price.ttc %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @price.product_id %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @price.currency_id %>
</p>

<p>
  <strong>Ht:</strong>
  <%= @price.ht %>
</p>

<p>
  <strong>Ttc:</strong>
  <%= @price.ttc %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>