config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :prices
  resources :currencies
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :title, presence: true
  validates :title, uniqueness: true
  has_many :prices, dependent: :delete_all
  has_many_attached :images, dependent: :delete_all

  before_destroy do
    images.purge
    prices.delete_all
  end

  def price_ml
    prices.where(currency_id: CURRENCY_ML.id).first
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title,
                                      :short_description,
                                      :long_description,
                                      :category_id,
                                      :stock,
                                      :weight,
                                      :dimensions,
                                      :dolibarr_id,
                                      images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :short_description %>
    <%= form.text_area :short_description %>
  </div>

  <div class="field">
    <%= form.label :long_description %>
    <%= form.text_area :long_description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :dimensions %>
    <%= form.text_field :dimensions %>
  </div>

  <div class="field">
    <%= form.label :dolibarr_id %>
    <%= form.number_field :dolibarr_id %>
  </div>

  <div class="field">
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">

  <div class='row products_categories'>
    <% Category.order(:title).each do |category| %>
      <%= link_to category do %>
        <% classe = @category && @category.id == category.id ? 'badge-primary' : 'badge-secondary badge-anim' %>
        <div><span class="badge badge-pill badge-category <%= classe %>"><%= category.title %></span></div>
      <% end %>
    <% end %>
  </div>

  <p id="notice"><%= notice %></p>

  <div class="row">
    <% if @products.count == 0 %>
      <div class='col-md-12 products_no_product'>Aucun produit dans cette catégorie pour le moment ...</div>
    <% end %>
    <% @products.each do |product| %>
      <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3">
        <%= link_to product do %>
          <div class="products_frame">
            <div class='products_image'>
              <% if product.images.attached? %>
                <%= image_tag product.images.first.variant(resize_to_limit: [200, 200]) %>
              <% else %>
                <%= image_tag 'no_image', size: '200x200' %>
              <% end %>
            </div>
            <div class="products_infos">
              <div class='products_title'><%= product.title.length>60 ? "#{product.title[0..60]}..." : product.title %></div>
              <div class="products_price">
                <% price = product.price_ml %>
                <%= number_to_currency(price.ttc, unit: price.currency.symbol, locale: :fr) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>
  
  <div class="row">
    <div class="col-md-12 col-lg-6">
      <div class="product_frame">
        <div class='product_image'>
          <% if @product.images.attached? %>
            <%= link_to url_for(@product.images.first), 'data-toggle': 'lightbox' do %>
              <%= image_tag @product.images.first.variant(resize_to_limit: [400, 400]) %>
            <% end %>
          <% else %>
            <%= image_tag 'no_image', size: "400x400" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-12 col-lg-6">
      <div class="product_frame">

        <%= link_to @product.category do %>
          <div><span class="badge badge-pill badge-secondary"><%= @product.category.title %></span></div>
        <% end %>

        <h2>
          <%= @product.title.length>80 ? "#{@product.title[0..80]}..." : @product.title %>
        </h2>

        <table class='product_table'>
          <tr>
            <td class='product_table_title'>
              <%= icon :fas, 'box-open' %>
              <strong>Etat</strong>
            </td>
            <td class='product_table_info'>
              <%= @product.second_hand ? 'Matériel d\'occasion' : 'Matériel neuf' %>
            </td>
          </tr>
          <tr>
            <td class='product_table_title'>
              <%= icon :fas, 'tag' %>
              <strong>Référence</strong>
            </td>
            <td class='product_table_info'>
              <%= @product.ref %>
            </td>
          </tr>
          <tr>
            <td class='product_table_title'>
              <%= icon :fas, 'cubes' %>
              <strong>Stock</strong>
            </td>
            <td class='product_table_info'>
              <%= @product.stock %> unité(s)
            </td>
          </tr>
        </table>

        <div class="product_price ">
          <% price = @product.price_ml %>
          <%= number_to_currency(price.ttc, unit: price.currency.symbol, locale: :fr) %>
        </div>

        <%= form_tag do %>
          <div class="input-group mb-3 product_buy_group">
            <%= number_field_tag 'quantity', 1 , class: 'form-control product_quantity', min: @product.stock.to_i>0 ? 1 : 0, max: @product.stock %>
            <div class="input-group-append">
              <span class="input-group-text product_buy_span" id="basic-addon2">
                <%= button_tag class: 'btn btn-primary product_buy' do %>
                  <%= icon :fas, 'shopping-basket' %>
                  Acheter
                <% end %>
              </span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="product_frame">
    <p>
      <h3>Description</h3>
      <%= @product.long_description.html_safe %>
    </p>

    <% if @product.weight %>
    <p>
      <strong>Poids:</strong>
      <%= @product.weight %>
    </p>
    <% end %>

    <% if @product.dimensions %>
    <p>
      <strong>Dimensions:</strong>
      <%= @product.dimensions %>
    </p>
    <% end %>

    <% if @product.url %>
    <p>
      <strong>Site du constructeur :  </strong>
      <%= link_to @product.url, @product.url, target: '_blank', class: 'link' %>
    </p>
    <% end %>

    <% if @product.images.count>1 %>
      <h3>Gallerie</h3>
      <div class="row">
        <% @product.images.each do |image| %>
          <div class="product_image_miniature">
            <%= link_to url_for(image), 'data-toggle': 'lightbox' do %>
              <%= image_tag image.variant(resize_to_limit: [90, 90]) %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

    <p>
      <strong>Dolibarr ID:</strong>
      <%= @product.dolibarr_id %>
    </p>
  </div>
</div>